//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestRunner.TestRunnerService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TestRunnerService.ITestRunnerService")]
    public interface ITestRunnerService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITestRunnerService/StartTesting", ReplyAction="http://tempuri.org/ITestRunnerService/StartTestingResponse")]
        void StartTesting(string testConfigFilePath);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITestRunnerService/StartTesting", ReplyAction="http://tempuri.org/ITestRunnerService/StartTestingResponse")]
        System.Threading.Tasks.Task StartTestingAsync(string testConfigFilePath);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITestRunnerService/GetTestingStatus", ReplyAction="http://tempuri.org/ITestRunnerService/GetTestingStatusResponse")]
        bool GetTestingStatus(ulong testingRunID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITestRunnerService/GetTestingStatus", ReplyAction="http://tempuri.org/ITestRunnerService/GetTestingStatusResponse")]
        System.Threading.Tasks.Task<bool> GetTestingStatusAsync(ulong testingRunID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITestRunnerService/GetProcessOutput", ReplyAction="http://tempuri.org/ITestRunnerService/GetProcessOutputResponse")]
        string GetProcessOutput(ulong testingRunID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITestRunnerService/GetProcessOutput", ReplyAction="http://tempuri.org/ITestRunnerService/GetProcessOutputResponse")]
        System.Threading.Tasks.Task<string> GetProcessOutputAsync(ulong testingRunID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITestRunnerService/GetProcessError", ReplyAction="http://tempuri.org/ITestRunnerService/GetProcessErrorResponse")]
        string GetProcessError(ulong testingRunID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITestRunnerService/GetProcessError", ReplyAction="http://tempuri.org/ITestRunnerService/GetProcessErrorResponse")]
        System.Threading.Tasks.Task<string> GetProcessErrorAsync(ulong testingRunID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITestRunnerService/GetAllProcesses", ReplyAction="http://tempuri.org/ITestRunnerService/GetAllProcessesResponse")]
        string[] GetAllProcesses();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITestRunnerService/GetAllProcesses", ReplyAction="http://tempuri.org/ITestRunnerService/GetAllProcessesResponse")]
        System.Threading.Tasks.Task<string[]> GetAllProcessesAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITestRunnerServiceChannel : TestRunner.TestRunnerService.ITestRunnerService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TestRunnerServiceClient : System.ServiceModel.ClientBase<TestRunner.TestRunnerService.ITestRunnerService>, TestRunner.TestRunnerService.ITestRunnerService {
        
        public TestRunnerServiceClient() {
        }
        
        public TestRunnerServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TestRunnerServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TestRunnerServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TestRunnerServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void StartTesting(string testConfigFilePath) {
            base.Channel.StartTesting(testConfigFilePath);
        }
        
        public System.Threading.Tasks.Task StartTestingAsync(string testConfigFilePath) {
            return base.Channel.StartTestingAsync(testConfigFilePath);
        }
        
        public bool GetTestingStatus(ulong testingRunID) {
            return base.Channel.GetTestingStatus(testingRunID);
        }
        
        public System.Threading.Tasks.Task<bool> GetTestingStatusAsync(ulong testingRunID) {
            return base.Channel.GetTestingStatusAsync(testingRunID);
        }
        
        public string GetProcessOutput(ulong testingRunID) {
            return base.Channel.GetProcessOutput(testingRunID);
        }
        
        public System.Threading.Tasks.Task<string> GetProcessOutputAsync(ulong testingRunID) {
            return base.Channel.GetProcessOutputAsync(testingRunID);
        }
        
        public string GetProcessError(ulong testingRunID) {
            return base.Channel.GetProcessError(testingRunID);
        }
        
        public System.Threading.Tasks.Task<string> GetProcessErrorAsync(ulong testingRunID) {
            return base.Channel.GetProcessErrorAsync(testingRunID);
        }
        
        public string[] GetAllProcesses() {
            return base.Channel.GetAllProcesses();
        }
        
        public System.Threading.Tasks.Task<string[]> GetAllProcessesAsync() {
            return base.Channel.GetAllProcessesAsync();
        }
    }
}
